/**
 * API Route: /api/wellness/sync
 * Manually sync wellness data from Terra
 */

import { NextRequest, NextResponse } from 'next/server'
import { terraClient, getTerraDateRange } from '@/lib/terra-client'
import { wellnessService } from '@/lib/wellness-service'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { userId, terraUserId, days = 7 } = body

    if (!userId || !terraUserId) {
      return NextResponse.json(
        { error: 'User ID and Terra User ID are required' },
        { status: 400 }
      )
    }

    // Get date range
    const { start_date, end_date } = getTerraDateRange(days)

    // Fetch daily activity data from Terra
    const dailyData = await terraClient.getDailyActivity({
      user_id: terraUserId,
      start_date,
      end_date
    })

    // Fetch workout/activity data
    const activityData = await terraClient.getActivity({
      user_id: terraUserId,
      start_date,
      end_date
    })

    // Fetch sleep data
    const sleepData = await terraClient.getSleep({
      user_id: terraUserId,
      start_date,
      end_date
    })

    // Process and store data
    const activities = []
    let totalPointsEarned = 0

    // Process daily data
    if (dailyData?.data) {
      for (const day of dailyData.data) {
        const activity = {
          id: '', // Will be generated by database
          user_id: userId,
          provider: 'terra' as const,
          date: new Date(day.metadata?.start_time || day.metadata?.date),
          steps: day.distance_data?.steps || 0,
          distance_meters: day.distance_data?.distance_meters || 0,
          calories_burned: day.calories_data?.total_burned_calories || 0,
          active_minutes: day.active_durations_data?.activity_seconds
            ? Math.round(day.active_durations_data.activity_seconds / 60)
            : 0,
          heart_rate_avg: day.heart_rate_data?.summary?.avg_hr_bpm,
          sleep_hours: undefined,
          points_earned: 0,
          synced_at: new Date(),
          created_at: new Date()
        }

        // Calculate points
        const points = wellnessService.calculateActivityPoints(activity)
        activity.points_earned = points
        totalPointsEarned += points

        activities.push(activity)

        // TODO: Save to database
        // await supabase.from('wellness_activities').upsert({...activity})
      }
    }

    // TODO: Update user's points in database
    // await supabase
    //   .from('wellness_points')
    //   .update({
    //     total_points: supabase.raw('total_points + ?', [totalPointsEarned]),
    //     monthly_points: supabase.raw('monthly_points + ?', [totalPointsEarned]),
    //     updated_at: new Date()
    //   })
    //   .eq('user_id', userId)

    console.log(`Synced ${activities.length} activities, ${totalPointsEarned} points earned`)

    return NextResponse.json({
      success: true,
      activities_synced: activities.length,
      points_earned: totalPointsEarned,
      date_range: { start_date, end_date }
    })

  } catch (error: any) {
    console.error('Sync error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to sync data' },
      { status: 500 }
    )
  }
}
