-- =====================================================
-- BimaBuddy Advanced - Real Indian Insurance Data
-- File: 006_seed_insurance_data.sql
-- Description: Real-time Indian health insurance policies data
-- Data Sources: IRDAI, Company websites, PolicyBazaar, 2025 data
-- =====================================================

-- =====================================================
-- INSURANCE COMPANIES
-- =====================================================
-- Based on IRDAI 2024-2025 data and claim settlement ratios

INSERT INTO insurance_companies (
  company_name,
  irdai_registration_number,
  website_url,
  customer_care_phone,
  customer_care_email,
  claim_settlement_ratio,
  network_hospitals_count,
  founded_year,
  rating,
  is_active
) VALUES
(
  'Star Health and Allied Insurance Company Limited',
  '112',
  'https://www.starhealth.in/',
  '1800 425 2255',
  'support@starhealth.in',
  99.21,
  14000,
  2006,
  4.5,
  true
),
(
  'HDFC ERGO Health Insurance Limited',
  '143',
  'https://www.hdfcergo.com/',
  '1800 2700 700',
  'customer.service@hdfcergo.com',
  99.16,
  13000,
  2007,
  4.6,
  true
),
(
  'Niva Bupa Health Insurance Company Limited',
  '148',
  'https://www.nivabupa.com/',
  '1800 258 6482',
  'support@nivabupa.com',
  99.99,
  8600,
  2007,
  4.7,
  true
),
(
  'Care Health Insurance Limited',
  '131',
  'https://www.careinsurance.com/',
  '1800 102 4477',
  'support@careinsurance.com',
  92.77,
  22900,
  2012,
  4.3,
  true
),
(
  'Aditya Birla Health Insurance Company Limited',
  '147',
  'https://www.adityabirlacapital.com/healthinsurance/',
  '1800 270 7000',
  'care.healthinsurance@adityabirlacapital.com',
  92.97,
  10051,
  2015,
  4.2,
  true
),
(
  'Reliance General Insurance Company Limited',
  '103',
  'https://www.reliancegeneral.co.in/',
  '1800 3009 ',
  'service@reliancegeneral.co.in',
  99.57,
  9500,
  2000,
  4.4,
  true
)
ON CONFLICT (company_name) DO UPDATE SET
  claim_settlement_ratio = EXCLUDED.claim_settlement_ratio,
  network_hospitals_count = EXCLUDED.network_hospitals_count,
  rating = EXCLUDED.rating,
  updated_at = NOW();

-- =====================================================
-- INSURANCE POLICIES - STAR HEALTH
-- =====================================================

-- Star Health Comprehensive Plan
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Comprehensive Insurance Plan',
  'Individual',
  500000,
  10000000,
  8500,
  'No Sub-Limit',
  0,
  60,
  90,
  30,
  48,
  14000,
  14000,
  99.21,
  7,
  18,
  65,
  99,
  1,
  25,
  true,
  true,
  95
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Health Assure Plan',
  'Individual',
  300000,
  7500000,
  7200,
  'No Sub-Limit',
  0,
  60,
  90,
  30,
  48,
  14000,
  14000,
  99.21,
  7,
  18,
  65,
  99,
  1,
  25,
  true,
  true,
  90
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Family Health Optima',
  'Family Floater',
  300000,
  25000000,
  12000,
  'No Sub-Limit',
  0,
  60,
  90,
  30,
  48,
  14000,
  14000,
  99.21,
  7,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  98
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Senior Citizen Red Carpet Health Policy',
  'Senior Citizen',
  100000,
  2500000,
  18500,
  'Up to Rs 5000 per day',
  10,
  60,
  90,
  0,
  12,
  14000,
  14000,
  99.21,
  7,
  60,
  75,
  99,
  1,
  10,
  true,
  true,
  85
);

-- =====================================================
-- INSURANCE POLICIES - HDFC ERGO
-- =====================================================

INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Optima Secure Individual',
  'Individual',
  500000,
  20000000,
  6500,
  'Single Private AC',
  0,
  60,
  180,
  30,
  48,
  13000,
  13000,
  99.16,
  8,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  92
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Optima Restore Family Floater',
  'Family Floater',
  300000,
  25000000,
  11500,
  'Single Private AC',
  0,
  60,
  180,
  30,
  48,
  13000,
  13000,
  99.16,
  8,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  94
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Optima Senior',
  'Senior Citizen',
  200000,
  10000000,
  16800,
  'Single AC Room',
  10,
  60,
  180,
  0,
  24,
  13000,
  13000,
  99.16,
  8,
  60,
  75,
  99,
  1,
  10,
  true,
  true,
  88
);

-- =====================================================
-- INSURANCE POLICIES - NIVA BUPA
-- =====================================================

INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Niva Bupa Health Insurance Company Limited'),
  'Niva Bupa Health Insurance Company Limited',
  'Niva Bupa ReAssure 2.0 Individual',
  'Individual',
  500000,
  10000000,
  8900,
  'No Room Rent Limit',
  0,
  60,
  180,
  0,
  0,
  8600,
  8600,
  99.99,
  5,
  18,
  65,
  99,
  1,
  30,
  true,
  true,
  96,
  '["Unlimited reinstatement of sum insured", "2-hour hospitalization coverage", "Booster+ benefit - carry forward up to 10x", "Day 1 coverage with Smart Health+ rider", "Lock the Clock feature", "Annual health check-up from day 1"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Niva Bupa Health Insurance Company Limited'),
  'Niva Bupa Health Insurance Company Limited',
  'Niva Bupa Health Companion Family Floater',
  'Family Floater',
  300000,
  10000000,
  13500,
  'No Room Rent Limit',
  0,
  60,
  180,
  30,
  48,
  8600,
  8600,
  99.99,
  5,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  93,
  '["Covers up to 19 relationships", "No room rent capping", "Day care procedures covered", "AYUSH treatments", "e-consultations", "Budget-friendly plan"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Niva Bupa Health Insurance Company Limited'),
  'Niva Bupa Health Insurance Company Limited',
  'Niva Bupa Senior First Plan',
  'Senior Citizen',
  500000,
  2500000,
  22500,
  'No Room Rent Limit',
  0,
  60,
  180,
  0,
  24,
  8600,
  8600,
  99.99,
  5,
  61,
  99,
  99,
  1,
  10,
  true,
  true,
  90,
  '["Age bands: 61-65, 66-70, 71-75, 76-80, 81-85, 86+", "Full sum insured restoration after first claim", "Pre-existing conditions covered after 2 years", "Gold and Platinum plan variants"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- =====================================================
-- INSURANCE POLICIES - CARE HEALTH
-- =====================================================

INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Care Health Insurance Limited'),
  'Care Health Insurance Limited',
  'Care Health Insurance Individual Plan',
  'Individual',
  300000,
  10000000,
  7800,
  'Single Private AC',
  0,
  60,
  180,
  30,
  48,
  22900,
  22900,
  92.77,
  2,
  18,
  65,
  99,
  1,
  20,
  true,
  true,
  87,
  '["Cashless claims settled within 2 hours", "Covers non-medical expenses", "Outpatient expenses covered", "Day care procedures", "100% claim settlement in FY 2023-24"]'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Care Health Insurance Limited'),
  'Care Health Insurance Limited',
  'Care Freedom Family Floater',
  'Family Floater',
  300000,
  25000000,
  10800,
  'Single Private AC',
  0,
  60,
  180,
  30,
  48,
  22900,
  22900,
  92.77,
  2,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  89,
  '["Comprehensive family coverage", "Largest network in India", "Fast claim processing", "Maternity coverage", "Newborn baby coverage"]'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Care Health Insurance Limited'),
  'Care Health Insurance Limited',
  'Care Senior Health Advantage',
  'Senior Citizen',
  300000,
  10000000,
  19500,
  'Single Private AC',
  50,
  60,
  180,
  0,
  24,
  22900,
  22900,
  92.77,
  2,
  60,
  99,
  99,
  1,
  5,
  false,
  true,
  82,
  '["No maximum entry age", "50% co-payment until 70 years", "Extra 10% co-payment after 70", "Designed for elderly coverage", "Pre-existing diseases covered"]'
);

-- =====================================================
-- INSURANCE POLICIES - ADITYA BIRLA
-- =====================================================

INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Aditya Birla Health Insurance Company Limited'),
  'Aditya Birla Health Insurance Company Limited',
  'Activ Health Platinum Enhanced Individual',
  'Individual',
  200000,
  20000000,
  9200,
  'Any room for 4L+, Single AC for lower',
  0,
  60,
  180,
  30,
  48,
  10051,
  10051,
  92.97,
  10,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  86,
  '["HealthReturns benefit", "Reload of sum insured", "Chronic Management Program", "Mental illness coverage", "Bariatric surgery coverage", "Cumulative bonus up to 100%"]'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Aditya Birla Health Insurance Company Limited'),
  'Aditya Birla Health Insurance Company Limited',
  'Activ Health Platinum Family Floater',
  'Family Floater',
  300000,
  20000000,
  14500,
  'Any room for 4L+, Single AC for lower',
  0,
  60,
  180,
  30,
  48,
  10051,
  10051,
  92.97,
  10,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  84,
  '["Family coverage with HealthReturns", "Wellness programs", "Reload benefit", "Mental health coverage", "Modern treatments covered"]'
);

-- =====================================================
-- INSURANCE POLICIES - RELIANCE GENERAL
-- =====================================================

INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Reliance General Insurance Company Limited'),
  'Reliance General Insurance Company Limited',
  'Reliance Health Infinity Individual',
  'Individual',
  300000,
  5000000,
  7500,
  'Single Private AC',
  0,
  30,
  60,
  30,
  48,
  9500,
  9500,
  99.57,
  9,
  18,
  65,
  99,
  1,
  20,
  true,
  true,
  83
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Reliance General Insurance Company Limited'),
  'Reliance General Insurance Company Limited',
  'Reliance Health Gain Family Floater',
  'Family Floater',
  500000,
  10000000,
  12800,
  'Single Private AC',
  0,
  30,
  60,
  30,
  48,
  9500,
  9500,
  99.57,
  9,
  18,
  65,
  99,
  1,
  50,
  true,
  true,
  80
);

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TABLE insurance_companies IS 'Major Indian health insurance companies with IRDAI 2024-2025 data';
COMMENT ON TABLE insurance_policies IS 'Real health insurance policies from top Indian insurers - 2025 data';
