-- =====================================================
-- BimaBuddy Advanced - Specialized Insurance Policies
-- File: 009_specialized_policies.sql
-- Description: Critical illness, maternity, and specialized health coverage
-- Data Sources: IRDAI, Company websites, PolicyBazaar 2025
-- Date: November 2025
-- =====================================================

-- =====================================================
-- CRITICAL ILLNESS INSURANCE POLICIES
-- =====================================================

-- HDFC ERGO Critical Illness - Platinum
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Critical Illness - Platinum Plan',
  'Individual',
  500000,
  1000000,
  8500,
  'N/A - Lump sum payout',
  0,
  0,
  0,
  3,
  0,
  13000,
  13000,
  99.16,
  15,
  18,
  65,
  99,
  1,
  0,
  false,
  true,
  91,
  '["Covers 15 major critical illnesses", "Cancer (all stages)", "Heart attack", "Kidney failure", "Stroke", "Heart valve replacement", "Paralysis", "Lump-sum payout on diagnosis", "90-day waiting period", "13000+ network hospitals", "CSR 95%+", "No hospitalization required for payout"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Critical Illness - Gold Plan',
  'Individual',
  300000,
  500000,
  5500,
  'N/A - Lump sum payout',
  0,
  0,
  0,
  3,
  0,
  13000,
  13000,
  99.16,
  15,
  18,
  65,
  99,
  1,
  0,
  false,
  true,
  88,
  '["Covers 11 major critical illnesses", "Cancer", "Heart attack", "Kidney failure", "Stroke", "Paralysis", "Heart valve replacement", "Lump-sum payout", "Lower premium tier", "90-day waiting period"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
),
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Critical Illness - Silver Plan',
  'Individual',
  200000,
  300000,
  3500,
  'N/A - Lump sum payout',
  0,
  0,
  0,
  3,
  0,
  13000,
  13000,
  99.16,
  15,
  18,
  65,
  99,
  1,
  0,
  false,
  true,
  85,
  '["Covers 8 major critical illnesses", "Cancer", "Heart attack", "Kidney failure", "Stroke", "Basic critical illness protection", "Most affordable tier", "90-day waiting period"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Niva Bupa CritiCare Plan
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Niva Bupa Health Insurance Company Limited'),
  'Niva Bupa Health Insurance Company Limited',
  'Niva Bupa CritiCare Plan',
  'Individual',
  500000,
  2000000,
  9200,
  'N/A - Lump sum payout',
  0,
  0,
  0,
  3,
  0,
  8600,
  8600,
  99.99,
  10,
  18,
  65,
  99,
  1,
  0,
  false,
  true,
  93,
  '["Covers 30+ critical illnesses", "Industry-best CSR 99.99%", "Cancer (all types)", "Heart conditions", "Neurological disorders", "Organ transplants", "Lump-sum benefit", "Multiple claim option", "90-day waiting period", "Premium waiver on first claim"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- ICICI Lombard Complete Health Insurance with Critical Illness Rider
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'ICICI Lombard General Insurance Company Limited'),
  'ICICI Lombard General Insurance Company Limited',
  'ICICI Lombard Complete Health with Critical Illness Rider',
  'Individual',
  500000,
  1000000,
  10500,
  'No Sub-Limit for 10L+',
  0,
  60,
  180,
  30,
  24,
  4000,
  4000,
  96.50,
  8,
  18,
  45,
  99,
  1,
  20,
  true,
  true,
  90,
  '["Base health coverage + Critical illness rider", "Covers 16 critical illnesses", "Lump-sum on critical illness diagnosis", "Regular health coverage continues", "Double protection", "No co-payment", "Wellness benefits included"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Star Health Cancer Care Gold
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Health Cancer Care Gold',
  'Individual',
  500000,
  2500000,
  7500,
  'No Sub-Limit',
  0,
  30,
  180,
  3,
  0,
  14000,
  14000,
  99.21,
  7,
  18,
  75,
  99,
  1,
  0,
  false,
  true,
  87,
  '["Cancer-specific coverage", "All stages of cancer covered", "Surgery, chemotherapy, radiation", "Hormone therapy", "Immunotherapy", "Targeted therapy", "Bone marrow transplant", "Second medical opinion", "Palliative care", "Reconstructive surgery post-cancer"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- =====================================================
-- MATERNITY INSURANCE POLICIES
-- =====================================================

-- Aditya Birla ActivOne Maternity Plan
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Aditya Birla Health Insurance Company Limited'),
  'Aditya Birla Health Insurance Company Limited',
  'Aditya Birla ActivOne Maternity Plan',
  'Individual',
  300000,
  1000000,
  15000,
  'Single Private AC',
  0,
  60,
  180,
  3,
  0,
  10051,
  10051,
  92.97,
  10,
  18,
  45,
  45,
  1,
  0,
  false,
  true,
  95,
  '["Lowest waiting period: 3 months", "Covers already pregnant women", "Normal and C-section delivery", "Pre-natal expenses", "Post-natal expenses", "Newborn baby coverage (90 days)", "Vaccinations included", "Complications coverage", "Maternity hospitalization", "Unique in market"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Care Joy Tomorrow Maternity Plan
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Care Health Insurance Limited'),
  'Care Health Insurance Limited',
  'Care Joy Tomorrow Maternity Plan',
  'Individual',
  300000,
  500000,
  13500,
  'Single Private AC',
  0,
  60,
  180,
  9,
  0,
  22900,
  22900,
  92.77,
  2,
  21,
  45,
  45,
  1,
  0,
  false,
  true,
  92,
  '["9-month waiting period", "₹3 lakh and ₹5 lakh options", "Covers maternity expenses", "Newborn baby expenses", "Pre-hospitalization costs", "Post-hospitalization costs", "Normal and C-section delivery", "Largest network: 22,900 hospitals", "Fast claim settlement: 2 hours"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Star Women Care Insurance Plan
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Women Care Insurance Plan',
  'Individual',
  500000,
  10000000,
  18000,
  'No Sub-Limit',
  0,
  60,
  180,
  24,
  48,
  14000,
  14000,
  99.21,
  7,
  18,
  75,
  99,
  1,
  10,
  true,
  true,
  90,
  '["Women-centric comprehensive coverage", "Covers already pregnant women", "24-month waiting period", "₹5 lakh to ₹1 crore coverage", "Maternity expenses", "Assisted reproductive treatments (IVF, IUI)", "Surrogacy coverage", "Newborn baby coverage", "Women-specific illnesses", "Ovarian cancer, breast cancer coverage", "PCOS, endometriosis treatment"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Niva Bupa Aspire Maternity Plan
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Niva Bupa Health Insurance Company Limited'),
  'Niva Bupa Health Insurance Company Limited',
  'Niva Bupa Aspire Maternity Plan',
  'Individual',
  500000,
  2000000,
  16500,
  'No Room Rent Limit',
  0,
  60,
  180,
  9,
  0,
  8600,
  8600,
  99.99,
  5,
  21,
  45,
  45,
  1,
  0,
  false,
  true,
  93,
  '["9-month to 2-year waiting period (variant-based)", "M-iracle Benefit: Carry forward unutilized sum insured", "Booster+ benefit: Up to 10x carry forward", "Industry-best CSR 99.99%", "Maternity coverage", "Newborn expenses from day 1", "Vaccinations covered", "Normal and C-section delivery", "Complications coverage"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- HDFC ERGO My:health Suraksha - Maternity Add-on
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO My:health Suraksha with Maternity',
  'Family Floater',
  500000,
  2500000,
  17500,
  'Single Private AC',
  0,
  60,
  180,
  12,
  48,
  13000,
  13000,
  99.16,
  8,
  18,
  45,
  45,
  1,
  25,
  true,
  true,
  89,
  '["Base health coverage + Maternity add-on", "12-month waiting period", "Normal and C-section delivery", "Newborn baby coverage (30 days)", "Pre and post natal care", "Maternity hospitalization", "Family floater with maternity", "Vaccination expenses", "Complications covered"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- =====================================================
-- SUPER TOP-UP / SUPPLEMENTARY POLICIES
-- =====================================================

-- HDFC ERGO Health Suraksha Top-up
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'HDFC ERGO Health Insurance Limited'),
  'HDFC ERGO Health Insurance Limited',
  'HDFC ERGO Health Suraksha Top-up',
  'Individual',
  500000,
  10000000,
  4000,
  'As per base policy',
  0,
  60,
  180,
  30,
  48,
  13000,
  13000,
  99.16,
  8,
  18,
  65,
  99,
  1,
  10,
  true,
  true,
  86,
  '["Super top-up plan", "Deductible: ₹3-5 lakh", "Covers expenses beyond base policy", "Lower premium than standalone", "Individual and family floater options", "Cumulative bonus benefit", "Restoration benefit", "Day care procedures", "Affordable coverage enhancement"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Niva Bupa Health Recharge
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Niva Bupa Health Insurance Company Limited'),
  'Niva Bupa Health Insurance Company Limited',
  'Niva Bupa Health Recharge Top-up',
  'Individual',
  500000,
  5000000,
  4500,
  'No Room Rent Limit',
  0,
  60,
  180,
  30,
  48,
  8600,
  8600,
  99.99,
  5,
  18,
  65,
  99,
  1,
  20,
  true,
  true,
  88,
  '["Top-up / Super top-up plan", "Works with any base policy", "No room rent capping", "Individual deductible or family deductible", "High coverage at low premium", "99.99% CSR", "Pre and post hospitalization", "Day care procedures"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- Star Health Super Surplus
INSERT INTO insurance_policies (
  company_id,
  company_name,
  policy_name,
  type_of_plan,
  sum_insured_min,
  sum_insured_max,
  annual_premium,
  room_rent_limit,
  co_payment,
  pre_hospitalization_days,
  post_hospitalization_days,
  waiting_period_months,
  pre_existing_disease_waiting_period_months,
  network_hospitals_count,
  cashless_hospitals_count,
  claim_settlement_ratio,
  claim_settlement_time_days,
  entry_age_min,
  entry_age_max,
  renewal_age_max,
  policy_term_years,
  renewal_bonus_percentage,
  restoration_benefit,
  is_active,
  popularity_score,
  key_features,
  tax_benefits
) VALUES
(
  (SELECT id FROM insurance_companies WHERE company_name = 'Star Health and Allied Insurance Company Limited'),
  'Star Health and Allied Insurance Company Limited',
  'Star Health Super Surplus',
  'Individual',
  300000,
  5000000,
  3800,
  'No Sub-Limit',
  0,
  60,
  90,
  30,
  48,
  14000,
  14000,
  99.21,
  7,
  18,
  65,
  99,
  1,
  15,
  true,
  true,
  84,
  '["Affordable top-up plan", "Deductible options available", "Works over existing policy", "14000+ network hospitals", "No sub-limits", "Enhances overall coverage", "Cumulative bonus", "Cost-effective expansion"]',
  'Tax benefits under Section 80D of Income Tax Act, 1961'
);

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TABLE insurance_policies IS 'Now includes 56+ policies: Base health, Critical illness, Maternity, Top-up plans - November 2025';

-- =====================================================
-- DATA SUMMARY
-- =====================================================
-- Specialized Policies Added: 15
--
-- Critical Illness Policies: 6
-- 1. HDFC ERGO Critical Illness (Platinum, Gold, Silver) - 8-15 illnesses covered
-- 2. Niva Bupa CritiCare - 30+ illnesses, industry-best CSR
-- 3. ICICI Lombard with Critical Illness Rider - 16 illnesses
-- 4. Star Health Cancer Care Gold - Cancer-specific coverage
--
-- Maternity Insurance Policies: 6
-- 1. Aditya Birla ActivOne - Lowest 3-month waiting period
-- 2. Care Joy Tomorrow - 9-month waiting, ₹3-5L coverage
-- 3. Star Women Care - Comprehensive women's health, IVF/surrogacy
-- 4. Niva Bupa Aspire - M-iracle benefit, carry forward sum insured
-- 5. HDFC ERGO My:health Suraksha - Family floater with maternity
--
-- Top-up / Super Top-up Policies: 3
-- 1. HDFC ERGO Health Suraksha Top-up - ₹5-100L, ₹4K premium
-- 2. Niva Bupa Health Recharge - Works with any base policy
-- 3. Star Health Super Surplus - ₹3-50L, ₹3.8K premium
--
-- Key Insights:
-- - Critical illness waiting period: 90 days (3 months)
-- - Maternity waiting periods: 3 months to 24 months
-- - Top-up plans offer 60-70% lower premiums vs standalone
-- - Critical illness premiums: ₹3,500-9,200/year
-- - Maternity premiums: ₹13,500-18,000/year
-- - Top-up premiums: ₹3,800-4,500/year
-- =====================================================
